// Main SDK entry point
export { default as CatalogClient, SearchQueryBuilder } from './CatalogClient';
export { default as Query } from './Query';

// Export all types (type-only exports)
export type {
  Category,
  TcgBrand,
  TcgProductType,
  SupportedLanguageCode,
  SortBy,
  SortOrder,
  Source,
  SharedTcgCardDetails,
  SharedTcgSealedDetails,
  TcgPlayerSku,
  TcgPlayerThirdParty,
  CardVariant,
  PokemonCardVariant,
  PokemonCardDetails,
  PokemonSealedDetails,
  YugiohCardDetails,
  YugiohSealedDetails,
  OnePieceCardDetails,
  OnePieceSealedDetails,
  RiftboundCardType,
  RiftboundCardSuperType,
  RiftboundCardDomain,
  RiftboundCardRarity,
  RiftboundCardVariant,
  RiftboundCardDetails,
  RiftboundSealedDetails,
  PokemonDetails,
  YugiohDetails,
  OnePieceDetails,
  RiftboundDetails,
  TcgDetails,
  VideoGameDetails,
  ConsoleDetails,
  BaseCatalogItem,
  PokemonCatalogItem,
  PokemonCardCatalogItem,
  PokemonSealedCatalogItem,
  YugiohCatalogItem,
  OnePieceCatalogItem,
  RiftboundCardCatalogItem,
  RiftboundSealedCatalogItem,
  RiftboundCatalogItem,
  VideoGameCatalogItem,
  ConsoleCatalogItem,
  CatalogItem,
  CatalogSearchFilters,
  CatalogSearchResponse,
  CatalogSearchItem,
  CatalogView,
  CatalogVariantSearchItem,
  AutocompleteSuggestion,
  AutocompleteResponse,
  PriceSnapshot,
  VariantPriceSnapshot,
} from './types';


export type {
  Illustrator,
  IllustratorsResponse,
} from './Illustrators/types';

// Export runtime values (type guards, constants, etc.)
export {
  SUPPORTED_LANGUAGE_CODES,
  isPokemonCatalogItem,
  isPokemonCardCatalogItem,
  isPokemonSealedCatalogItem,
  isYugiohCatalogItem,
  isOnePieceCatalogItem,
  isRiftboundCatalogItem,
  isRiftboundCardCatalogItem,
  isRiftboundSealedCatalogItem,
  isVideoGameCatalogItem,
  isConsoleCatalogItem,
  isTcgCatalogItem,
  isCatalogVariantSearchItem,
} from './types';

// Export utilities
export { buildURL, detectContext } from './utils';

// omni read API (/api/v2)
export { default as CatalogClientV2, CatalogApiError } from './v2/CatalogClientV2';
export { isPokemonCardProduct, isRiftboundCardProduct } from './v2/types';
export type {
  TcgGameSlug,
  LanguageCode,
  LifecycleStatus,
  TcgGameRef,
  SeriesRef,
  IllustratorRef,
  IllustratorListItem,
  LocalizedNames,
  CatalogSet,
  CatalogSeries,
  CatalogCharacter,
  PriceCondition,
  ConditionPrice,
  VariantPricing,
  CatalogVariant,
  PokemonCardDetailsV2,
  RiftboundCardDetailsV2,
  ProductType,
  PokemonCardProduct,
  RiftboundCardProduct,
  SealedProduct,
  CatalogProduct,
  VariantPrices,
  ProductSummary,
  Page,
  SearchSort,
  SearchParams,
  SearchPage,
  SuggestedCharacter,
  SuggestedSet,
  SuggestedProduct,
  Suggestions,
} from './v2/types';
